# Generated by Django 2.2.4 on 2019-08-16 06:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('BS', 'Bible Study'), ('SR', 'Sex and Relationships'), ('ME', 'Movies and Entertainment'), ('PO', 'Political')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('pronouns', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('connection', models.CharField(choices=[('1-Acknowledgement', 'Acknowledgement'), ('2-Dialogue/Emotional Connection', 'Dialogue/Emotional Connection'), ('3-Intersection', 'Intersection'), ('4-Invitation', 'Invitation')], max_length=20)),
                ('participation', models.CharField(choices=[('1-Connection', 'Connection'), ('2-Contact', 'Contact'), ('3-Visitor', 'Visitor'), ('4-Participant', 'Participant'), ('5-Potential Leader', 'Potential Leader'), ('6-Leader', 'Leader'), ('7-Leader-Trainer', 'Leader-Trainer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendees', models.ManyToManyField(related_name='attendees', to='gatherings.Person')),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherings.Gathering')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='gatherings.Person')),
            ],
        ),
        migrations.AddField(
            model_name='gathering',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherings.Person'),
        ),
    ]
