# Generated by Django 2.2.4 on 2020-02-13 06:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrences', recurrence.fields.RecurrenceField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('EV', 'Event'), ('CL', 'Class'), ('GR', 'Group')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtableID', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('leadership_interested', models.BooleanField(null=True)),
                ('leadership_trained', models.BooleanField(null=True)),
                ('connection', models.CharField(blank=True, choices=[('1-Acknowledgement', 'Acknowledgement'), ('2-Dialogue/Emotional Connection', 'Dialogue/Emotional Connection'), ('3-Intersection', 'Intersection'), ('4-Invitation', 'Invitation')], max_length=40, null=True)),
                ('participation', models.CharField(blank=True, choices=[('1-Connection', 'Connection'), ('2-Contact', 'Contact'), ('3-Visitor', 'Visitor'), ('4-Participant', 'Participant'), ('5-Potential Leader', 'Potential Leader'), ('6-Leader', 'Leader'), ('7-Leader-Trainer', 'Leader-Trainer')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtableID', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('location', models.CharField(default='', max_length=30)),
                ('attendees', models.ManyToManyField(blank=True, related_name='sessions_attended', to='gatherings.Person')),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherings.Gathering')),
                ('leader', models.ManyToManyField(related_name='sessions_lead', to='gatherings.Person')),
            ],
        ),
        migrations.AddField(
            model_name='gathering',
            name='authors',
            field=models.ManyToManyField(to='gatherings.Person'),
        ),
    ]
