# Generated by Django 2.2.4 on 2019-08-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='leadership_interested',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='leadership_trained',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
