# Generated by Django 2.2.4 on 2020-02-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gathering', serialize=False, to='schedule.Event'),
        ),
    ]
