# Generated by Django 2.2.4 on 2020-02-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
