# Generated by Django 2.2.4 on 2019-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0002_auto_20190816_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='leadership_interested',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='leadership_trained',
            field=models.BooleanField(null=True),
        ),
    ]
