# Generated by Django 2.2.4 on 2019-08-16 06:50
import requests, phonenumbers
from django.db import migrations
from django.conf import settings
from gatherings.serializers import GatheringSerializer
from gatherings.models import Gathering


def gatherings_from_airtable(apps, schema_editor):
    response = requests.get('https://api.airtable.com/v0/apps7BNP7qTwR1BGF/Classes',
                            params={'api_key': settings.AIRTABLE_API_KEY})
    records = response.json()
    while True:
        gatherings = records['records']
        for gathering in gatherings:
            fields = gathering['fields']
            fields = {k.translate({32: None}): v for k, v in fields.items()}
            fields = {k.replace('?', ''): v for k, v in fields.items()}
            fields['airtableID'] = gathering['id']
            serializer = GatheringSerializer(data=fields)
            serializer.is_valid()
            print(serializer.validated_data)
            serializer.save()
        if 'offset' not in records:
            break
        offset = records['offset']
        response = requests.get('https://api.airtable.com/v0/apps7BNP7qTwR1BGF/Classes',
                                params={'api_key': settings.AIRTABLE_API_KEY,
                                        'offset': offset})
        records = response.json()


def delete_gatherings(apps, schema_editor):
    Gathering = apps.get_model('gatherings', 'Gathering')
    Gathering.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0002_people'),
    ]

    operations = [
        migrations.RunPython(gatherings_from_airtable,
                             delete_gatherings)
    ]
