# Generated by Django 2.2.4 on 2019-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0003_gatherings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(related_name='sessions_attended', to='gatherings.Person'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='gathering',
        ),
        migrations.AddField(
            model_name='session',
            name='gathering',
            field=models.ManyToManyField(to='gatherings.Gathering'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='leader',
        ),
        migrations.AddField(
            model_name='session',
            name='leader',
            field=models.ManyToManyField(related_name='sessions_lead', to='gatherings.Person'),
        ),
    ]
