# Generated by Django 2.2.4 on 2020-02-13 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0003_gathering_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 54, 1, 172063)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gathering',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 54, 13, 205780)),
            preserve_default=False,
        ),
    ]
