# Generated by Django 2.2.4 on 2019-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0005_auto_20190816_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connection',
            field=models.CharField(choices=[('1-Acknowledgement', 'Acknowledgement'), ('2-Dialogue/Emotional Connection', 'Dialogue/Emotional Connection'), ('3-Intersection', 'Intersection'), ('4-Invitation', 'Invitation')], max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='participation',
            field=models.CharField(choices=[('1-Connection', 'Connection'), ('2-Contact', 'Contact'), ('3-Visitor', 'Visitor'), ('4-Participant', 'Participant'), ('5-Potential Leader', 'Potential Leader'), ('6-Leader', 'Leader'), ('7-Leader-Trainer', 'Leader-Trainer')], max_length=40),
        ),
    ]
