# Generated by Django 2.2.4 on 2019-08-27 08:18

from django.db import migrations

def populate_gatherings(apps, schema_editor):
    Session = apps.get_model('gatherings', 'Session')
    for session in Session.objects.all():
        session.gathering_temp = session.gathering.all().first()
        session.save()

def undo_population(apps, schema_editor):
    Session = apps.get_model('gatherings', 'Session')
    for session in Session.objects.all():
        if session.gathering_temp:
            session.gathering.add(session.gathering_temp)

class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0005_auto_20190827_0317'),
    ]

    operations = [
        migrations.RunPython(populate_gatherings, undo_population)
    ]
