# Generated by Django 2.2.4 on 2019-08-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0006_auto_20190827_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='gathering',
        ),
    ]
