# Generated by Django 2.2.4 on 2019-08-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0007_remove_session_gathering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='gathering_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherings.Gathering'),
        ),
    ]
