# Generated by Django 2.2.4 on 2019-08-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0008_auto_20190827_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='gathering_temp',
            new_name='gathering',
        ),
    ]
