# Generated by Django 2.2.4 on 2019-08-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0009_auto_20190827_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
