# Generated by Django 2.2.4 on 2019-08-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0010_session_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
