# Generated by Django 2.2.4 on 2019-08-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0011_auto_20190827_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='airtableID',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
