# Generated by Django 2.2.4 on 2019-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0012_auto_20190827_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
