# Generated by Django 2.2.4 on 2019-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0014_auto_20190827_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='airtableID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='sessions_attended', to='gatherings.Person'),
        ),
    ]
