# Generated by Django 2.2.4 on 2019-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0015_auto_20190827_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='airtableID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
