# Generated by Django 2.2.4 on 2019-08-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0016_auto_20190827_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='category',
            field=models.CharField(choices=[('EV', 'Event'), ('CL', 'Class'), ('GR', 'Group')], max_length=2),
        ),
    ]
