# Generated by Django 2.2.4 on 2019-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0018_auto_20191114_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='airtableID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
