# Generated by Django 2.2.4 on 2019-11-14 21:28

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0019_auto_20191114_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='dates',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
