# Generated by Django 2.2.4 on 2019-11-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0020_auto_20191114_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='dates_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='description',
            field=models.TextField(),
        ),
    ]
